model:
  saved_model_path: ./models/train_dataset
  model_name_or_path: klue/roberta-large
  config_name: null
  tokenizer_name: null

data:
  dataset_name: ../data/test_dataset
  overwrite_cache: false
  preprocessing_num_workers: null
  max_seq_length: 384 
  pad_to_max_length: true
  doc_stride: 96
  max_answer_length: 30
  eval_retrieval: true
  num_clusters: 64
  top_k_retrieval: 40
  use_faiss: false

train:
  output_dir: ./outputs/test_dataset/
  do_predict: true
custom:
  retrieval_type: sparse
  sparse_retrieval_type: bm25