model:
  saved_model_path: ./models/train_dataset/
  model_name_or_path: 'klue/bert-base'
  config_name: null
  tokenizer_name: null


data:
  data_path: '/data/ephemeral/data'
  test_dataset_name: '/data/ephemeral/data/test_dataset'
  overwrite_cache: false
  preprocessing_num_workers: null
  max_seq_length: 384
  pad_to_max_length: true
  doc_stride: 128
  max_answer_length: 30
  eval_retrieval: true
  num_clusters: 64
  top_k_retrieval: 20
  use_faiss: false
  which_retrieval: dense
train:
  output_dir: ./outputs/test_dataset/
  do_predict: true
