model:
  model_name_or_path: klue/roberta-large
  config_name: null
  tokenizer_name: null


data:
  dataset_name: 
  overwrite_cache: false
  preprocessing_num_workers: null
  max_seq_length: 384
  pad_to_max_length: false
  doc_stride: 128
  max_query_length: 30
  eval_retrieval: true
  num_clusters: 64
  top_k_retrieval: 10
  use_faiss: false

train:
  output_dir: ./outputs/train_dataset
  do_train: true
  do_eval: true
  overwrite_output_dir: true
  report_to: 'wandb'
  per_device_train_batch_size: 8
  per_device_eval_batch_size: 8
  logging_strategy: 'steps'
  logging_steps: 50
  evaluation_strategy: 'epoch'
  save_strategy: 'epoch'
  save_total_limit: 2
  num_train_epochs: 5
  warmup_steps: 300
  seed: 42
  dataloader_num_workers: 4
  logging_first_step: true